---
version: "3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - /volume1/homes/goncalo/docker/jackett:/config
      - /volume1/video/data:/downloads
      - /volume1/video/data:/data
    ports:
      - 9117:9117
    restart: unless-stopped
    env_file:
      - ./compose.env
    networks:
      - transmission
    labels:
      - traefik.enable=true
      - traefik.backend=jackett
      - traefik.docker.network=transmission
      - traefik.port=9117
      - "traefik.frontend.rule=PathPrefix:/jackett"
      - com.centurylinklabs.watchtower.enable=true
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file:
      - ./compose.env
    volumes:
      - /volume1/homes/goncalo/docker/radarr:/config
      - /volume1/video/movies:/movies
      - /volume1/video/data:/downloads
      - /volume1/video/data:/data
      - /etc/localtime:/etc/localtime:ro
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 7878:7878
    networks:
      - transmission
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.backend=radarr
      - traefik.docker.network=transmission
      - traefik.port=7878
      - "traefik.frontend.rule=PathPrefix:/radarr"
      - com.centurylinklabs.watchtower.enable=true
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    env_file:
      - ./compose.env
    volumes:
      - /volume1/homes/goncalo/docker/sonarr:/config
      - /volume1/video/tv:/tv
      - /volume1/video/data:/downloads
      - /volume1/video/data:/data
      - /etc/localtime:/etc/localtime:ro
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 8989:8989
    networks:
      - transmission
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.backend=sonarr
      - traefik.docker.network=transmission
      - traefik.port=8989
      - "traefik.frontend.rule=PathPrefix:/sonarr"
      - com.centurylinklabs.watchtower.enable=true
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
     - /dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /volume1/homes/goncalo/docker/vpn/resolv.conf:/etc/resolv.conf
      - /volume1/homes/goncalo/docker/transmission:/config
      - /volume1/video/data:/downloads
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./compose.env
      - ./transmission.env
    networks:
      - transmission
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
networks:
  transmission:
    driver: bridge
